### ISSUE TITLE
Request for Python 3.9.7 for aarch624

### ISSUE THREAD

**Issue by unknown-user456** [Termux-pod/termux-pod#10]
can you please upload the deb file of python 3.9.7 for aarch64?

**Comment by Abu0Ali** [comment]
Yes please, I've searched for it but couldn't find it anywhere

**Comment by Elyanes** [comment]
It would be useful for me too !

**Comment by kcubeterm** [comment]
Go and look for your respective architecture, i have uploaded debfile of python 3.9.7

**Comment by tomyprs** [comment]
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
