### ISSUE TITLE
cannot locate symbol "ffi_type_double" error for php7

### ISSUE THREAD

**Issue by Yang-qwq** [Termux-pod/termux-pod#14]
**I'm not a native English speaker and I can't speak Englist well, so I'm using translation software. If you don't understand what I'm saying, I'm sorry**

I tried to install php7 from the DEB package, and my terminal output is as follows
```bash
 u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  ls
Readme.md  php-apache_7.4.12_aarch64.deb  php-fpm_7.4.12_aarch64.deb  php-pgsql_7.4.12_aarch64.deb  php_7.4.12_aarch64.deb
 u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  sv-disable httpd
 u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  dpkg -i php_7.4.12_aarch64.deb
dpkg: warning: downgrading php from 8.1.0-2 to 7.4.12
(Reading database ... 35939 files and directories currently installed.)
Preparing to unpack php_7.4.12_aarch64.deb ...
Unpacking php (7.4.12) over (8.1.0-2) ...
Setting up php (7.4.12) ...
 u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
```
And then, it has an error below:
```bash
CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
```

Then I tried to reinstall libffi and libllvm, but it still didn't work:
```bash
apt reinstall libffi libffi-static && apt reinstall libllvm libllvm-static
(some output)
 u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
```
How to solve this problem? If you know, Please tell me.

**Comment by brnyza** [comment]
> **I'm not a native English speaker and I can't speak Englist well, so I'm using translation software. If you don't understand what I'm saying, I'm sorry**
> 
> I tried to install php7 from the DEB package, and my terminal output is as follows
> 
> ```shell
>  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  ls
> Readme.md  php-apache_7.4.12_aarch64.deb  php-fpm_7.4.12_aarch64.deb  php-pgsql_7.4.12_aarch64.deb  php_7.4.12_aarch64.deb
>  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  sv-disable httpd
>  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  dpkg -i php_7.4.12_aarch64.deb
> dpkg: warning: downgrading php from 8.1.0-2 to 7.4.12
> (Reading database ... 35939 files and directories currently installed.)
> Preparing to unpack php_7.4.12_aarch64.deb ...
> Unpacking php (7.4.12) over (8.1.0-2) ...
> Setting up php (7.4.12) ...
>  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
> ```
> 
> And then, it has an error below:
> 
> ```shell
> CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
> ```
> 
> Then I tried to reinstall libffi and libllvm, but it still didn't work:
> 
> ```shell
> apt reinstall libffi libffi-static && apt reinstall libllvm libllvm-static
> (some output)
>  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
> CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
> ```
> 
> How to solve this problem? If you know, Please tell me.

Did you find a solution for it?

**Comment by Yang-qwq** [comment]
> > **I'm not a native English speaker and I can't speak Englist well, so I'm using translation software. If you don't understand what I'm saying, I'm sorry**
> > I tried to install php7 from the DEB package, and my terminal output is as follows
> > ```shell
> >  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  ls
> > Readme.md  php-apache_7.4.12_aarch64.deb  php-fpm_7.4.12_aarch64.deb  php-pgsql_7.4.12_aarch64.deb  php_7.4.12_aarch64.deb
> >  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  sv-disable httpd
> >  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  dpkg -i php_7.4.12_aarch64.deb
> > dpkg: warning: downgrading php from 8.1.0-2 to 7.4.12
> > (Reading database ... 35939 files and directories currently installed.)
> > Preparing to unpack php_7.4.12_aarch64.deb ...
> > Unpacking php (7.4.12) over (8.1.0-2) ...
> > Setting up php (7.4.12) ...
> >  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then, it has an error below:
> > ```shell
> > CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then I tried to reinstall libffi and libllvm, but it still didn't work:
> > ```shell
> > apt reinstall libffi libffi-static && apt reinstall libllvm libllvm-static
> > (some output)
> >  u0_a156@localhost  ~/termux-pod/aarch64/Php7   main  php -v
> > CANNOT LINK EXECUTABLE "php": cannot locate symbol "ffi_type_double" referenced by "/usr/bin/php" ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How to solve this problem? If you know, Please tell me.
> 
> Did you find a solution for it?

---

I'm not sure,but there seems already have a PHP package now
```bash
~ $ php
The program php is not installed. Install it by executing:
 pkg install php
or
 pkg install php7

~ $ apt info php7
Package: php7
Version: 7.4.27
Maintainer: @xtkoba
Installed-Size: 45.9 MB
Depends: freetype, libandroid-glob, libandroid-support, libbz2, libcrypt, libcurl, libgd, libgmp, libiconv, liblzma, libsqlite, libxml2, libxslt, libzip, oniguruma, openssl, pcre2, readline, zlib, libicu, libffi, tidy
Conflicts: php, php-mysql, php-dev
Homepage: https://php.net
Download-Size: 7568 kB
APT-Sources: https://termux.mentality.rip/termux-main stable/main aarch64 Packages
Description: Server-side, HTML-embedded scripting language
```

**Comment by brnyza** [comment]
Thank you!
The command worked very well!
pkg install php7
