### ISSUE TITLE
Which path should i use for dpkg?

### ISSUE THREAD

**Issue by birhbre** [Termux-pod/termux-pod#15]
im struggling to find a 3.9.7 aarch64 path to dpkg it. can somebody help me with that?

**Comment by kcubeterm** [comment]
Python 3.9.7 ? 
https://github.com/Termux-pod/termux-pod/blob/main/aarch64/python/python-3.9.7/python_3.9.7_aarch64.deb 

Download it from here.

**Comment by birhbre** [comment]
it says "no such file or directory"

**Comment by kcubeterm** [comment]
```
wget 'https://github.com/Termux-pod/termux-pod/blob/main/aarch64/python/python-3.9.7/python_3.9.7_aarch64.deb?raw=true' -O py.deb

dpkg -i py.deb
```
