### ISSUE TITLE
Permintaan python untuk armv8l

### ISSUE THREAD

**Issue by Itongmn** [Termux-pod/termux-pod#6]
Minta di buati file python untuk armv8l
Terimakasih

**Comment by kcubeterm** [comment]
Can't understand your language

**Comment by Itongmn** [comment]
Ask to create a python file for armv8l
Thank you

Pada tanggal Jum, 16 Jul 2021 17:43, Krishna Kanhaiya <
***@***.***> menulis:

**Comment by kcubeterm** [comment]
Armv8 is 64 bit and is here https://github.com/Termux-pod/termux-pod/tree/main/arch64/python
